- name: Configure network settings
  template:
    src: network_settings.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Restart network service

- name: Ensure network service is running
  service:
    name: networking
    state: started
    enabled: true
  tags:
    - network