- name: Configure SSH service
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSH service

- name: Ensure SSH service is running
  service:
    name: sshd
    state: started
    enabled: true
  tags:
    - ssh